/**
 * Regenerate apps/web/src/lib/lexicon.ts from a Vosk model's word list.
 *
 *   tar xzf apps/web/public/models/vosk-model-small-ja-0.22.tar.gz -C /tmp
 *   bun scripts/lexicon-forms.ts /tmp/vosk-model-small-ja-0.22
 *
 * A grammar may only contain words the model actually has, so every candidate
 * spelling is checked against graph/words.txt rather than assumed. Run this
 * whenever the model changes — the forms differ between models.
 */
import { DECKS } from '../apps/web/src/lib/kana';

/** Local, so this script needs nothing from the web workspace but the tables. */
function toKatakana(s: string): string {
  return [...s]
    .map((c) => {
      const code = c.codePointAt(0)!;
      return code >= 0x3041 && code <= 0x3096 ? String.fromCodePoint(code + 0x60) : c;
    })
    .join('');
}

const modelDir = process.argv[2];
if (!modelDir) {
  console.error('usage: bun scripts/lexicon-forms.ts <extracted-model-dir>');
  process.exit(1);
}

const wordsFile = Bun.file(`${modelDir}/graph/words.txt`);
if (!(await wordsFile.exists())) {
  console.error(`no ${modelDir}/graph/words.txt — is that an extracted Vosk model?`);
  process.exit(1);
}

const known = new Set(
  (await wordsFile.text()).split('\n').map((line) => line.split(' ')[0] ?? ''),
);

/** The kana of the vowel a mora ends on — きゃ ends on あ, not ゃ. */
const VOWEL_KANA: Record<string, string> = { a: 'あ', i: 'い', u: 'う', e: 'え', o: 'お' };

const hiragana = DECKS.filter((d) => d.script === 'hiragana');
const lines: string[] = [];
let forms = 0;

for (const deck of hiragana) {
  for (const card of deck.cards) {
    const kana = card.kana;
    const vowel = VOWEL_KANA[card.col];
    const candidates = [
      kana,
      toKatakana(kana),
      `${kana}ー`,
      `${toKatakana(kana)}ー`,
      // Held longer, a mora is spelled with its own vowel repeated: か → かあ.
      // Doubling the mora itself would be wrong for か (かか is ka-ka, two
      // moras) — except for ん, which has no vowel and whose held form really
      // is んん, and which the sokuon spelling んっ also writes.
      ...(card.row === 'N'
        ? [`${kana}${kana}`, `${toKatakana(kana)}${toKatakana(kana)}`, `${kana}っ`]
        : vowel
          ? [`${kana}${vowel}`, `${toKatakana(kana)}${toKatakana(vowel)}`]
          : []),
    ];
    const present = [...new Set(candidates.filter((w) => known.has(w)))];
    forms += present.length;
    lines.push(`  '${kana}': [${present.map((f) => `'${f}'`).join(', ')}],`);
  }
}

const header = `/**
 * Every spelling of a mora that vosk-model-small-ja-0.22 actually has in its
 * lexicon — generated by checking graph/words.txt, not guessed.
 *
 * Why this exists: a learner naming a kana in isolation holds the vowel far
 * longer than the same mora inside a word. Japanese contrasts vowel length
 * phonemically and the model has separate phones for it (a vs a:), so a held
 * «い» is properly transcribed «いい» or «いー» — neither of which was in a
 * grammar built from the bare kana. The decoder had nowhere to put the sound
 * except «[unk]».
 *
 * All of these are the same reading, so accepting any of them is not a
 * loosened match: あ and ああ are both /a/, never a different mora.
 *
 * Regenerate with scripts/lexicon-forms.ts against a new model.
 */
export const LEXICON_FORMS: Record<string, string[]> = {
`;

await Bun.write('apps/web/src/lib/lexicon.ts', `${header}${lines.join('\n')}\n};\n`);
console.log(`${forms} forms for ${lines.length} moras -> apps/web/src/lib/lexicon.ts`);
