/**
 * JLPT N5–N3 kanji, ordered by how often they appear in print (Mainichi
 * Shimbun frequency rank, 1 = most frequent). Generated from the `kanji-data`
 * package (MIT, derived from KANJIDIC2) and checked against the recogniser's
 * own word list — a reading it cannot say is not offered as an answer.
 *
 * A card is one character and accepts the readings it has on its own —
 * okurigana stems, bound prefixes and suffixes are not among them. VISION.md
 * asks for readings inside real words, which is the right end state and needs
 * a vetted vocabulary list; deriving one from this dataset automatically
 * yields 五十 read 「い」 and 三人 read 「みたり」, archaic readings nobody should
 * be taught. See scripts/kanji-data.ts.
 *
 * Regenerate with: bun run kanji
 */
export interface KanjiEntry {
  /** The character. */
  k: string;
  /** JLPT level: 5, 4 or 3. */
  n: number;
  /** Newspaper frequency rank; lower is more common. */
  f: number;
  /** Accepted readings, in both scripts, filtered to the model's lexicon. */
  r: string[];
  /** English senses, the most useful one first. */
  m: string[];
}

export const KANJI: KanjiEntry[] = [
  { k: '日', n: 5, f: 1, r: ['じつ', 'にち', 'ひ', 'ヒ'], m: ["day","Japan","counter for days","sun"] },
  { k: '一', n: 5, f: 2, r: ['いち', 'イチ', 'いつ'], m: ["one"] },
  { k: '国', n: 5, f: 3, r: ['こく', 'コク', 'くに', 'クニ'], m: ["country"] },
  { k: '人', n: 5, f: 5, r: ['じん', 'ジン', 'にん', 'ニン', 'ひと', 'ヒト'], m: ["person"] },
  { k: '年', n: 5, f: 6, r: ['ねん', 'ネン', 'とし', 'トシ'], m: ["year","counter for years"] },
  { k: '大', n: 5, f: 7, r: ['たい', 'タイ', 'だい', 'ダイ'], m: ["large","big"] },
  { k: '十', n: 5, f: 8, r: ['じゅう', 'と', 'ト', 'とお'], m: ["ten"] },
  { k: '二', n: 5, f: 9, r: ['じ', 'ジ', 'に', 'ニ', 'ふた', 'フタ'], m: ["two"] },
  { k: '本', n: 5, f: 10, r: ['ほん', 'ホン', 'もと', 'モト'], m: ["book","counter for long cylindrical things","main","origin","present","real","true"] },
  { k: '中', n: 5, f: 11, r: ['ちゅう', 'チュウ', 'うち', 'ウチ', 'なか', 'ナカ'], m: ["in","center","inside","mean","middle"] },
  { k: '長', n: 5, f: 12, r: ['ちょう', 'チョウ', 'おさ'], m: ["long","leader","senior","superior"] },
  { k: '出', n: 5, f: 13, r: ['しゅつ', 'すい', 'スイ'], m: ["exit","come out","go out","leave","protrude","put out"] },
  { k: '三', n: 5, f: 14, r: ['さん', 'サン', 'み', 'ミ'], m: ["three"] },
  { k: '時', n: 5, f: 16, r: ['じ', 'ジ', 'とき', 'トキ'], m: ["time","hour"] },
  { k: '行', n: 5, f: 20, r: ['あん', 'アン', 'ぎょう', 'こう', 'コウ'], m: ["going","act","bank","carry out","conduct","journey","line","row"] },
  { k: '見', n: 5, f: 22, r: ['けん', 'ケン'], m: ["see","chances","hopes","idea","look at","opinion","visible"] },
  { k: '月', n: 5, f: 23, r: ['がつ', 'ガツ', 'げつ', 'つき', 'ツキ'], m: ["month","moon"] },
  { k: '後', n: 5, f: 26, r: ['こう', 'コウ', 'ご', 'ゴ', 'あと', 'アト', 'うしろ', 'のち'], m: ["behind","back","later"] },
  { k: '前', n: 5, f: 27, r: ['ぜん', 'ゼン', 'まえ'], m: ["in front","before"] },
  { k: '生', n: 5, f: 29, r: ['しょう', 'ショウ', 'せい', 'セイ', 'うまれ', 'き', 'キ', 'なま', 'ナマ'], m: ["life","birth","genuine"] },
  { k: '五', n: 5, f: 31, r: ['ご', 'ゴ', 'いつ'], m: ["five"] },
  { k: '間', n: 5, f: 33, r: ['かん', 'カン', 'けん', 'ケン', 'あい', 'アイ', 'あいだ', 'アイダ', 'ま', 'マ'], m: ["interval","space"] },
  { k: '上', n: 5, f: 35, r: ['しょう', 'ショウ', 'じょう', 'うえ', 'ウエ', 'かみ', 'カミ'], m: ["above","up"] },
  { k: '東', n: 5, f: 37, r: ['とう', 'トウ', 'ひがし', 'ヒガシ'], m: ["east"] },
  { k: '四', n: 5, f: 47, r: ['し', 'シ', 'よ', 'ヨ', 'よん', 'ヨン'], m: ["four"] },
  { k: '今', n: 5, f: 49, r: ['きん', 'キン', 'こん', 'コン', 'いま', 'イマ'], m: ["now"] },
  { k: '金', n: 5, f: 53, r: ['きん', 'キン', 'こん', 'コン', 'ごん', 'ゴン', 'かね', 'カネ'], m: ["gold"] },
  { k: '九', n: 5, f: 55, r: ['きゅう', 'キュウ', 'く', 'ク', 'ここの'], m: ["nine"] },
  { k: '入', n: 5, f: 56, r: ['じゅ', 'ジュ', 'にゅう'], m: ["enter","insert"] },
  { k: '学', n: 5, f: 63, r: ['がく', 'ガク'], m: ["study","learning","science"] },
  { k: '高', n: 5, f: 65, r: ['こう', 'コウ', 'たか', 'タカ'], m: ["tall","expensive","high"] },
  { k: '円', n: 5, f: 69, r: ['えん', 'エン', 'まる', 'マル'], m: ["circle","round","yen"] },
  { k: '子', n: 5, f: 72, r: ['し', 'シ', 'す', 'ス', 'つ', 'ツ', 'こ', 'コ', 'ね', 'ネ'], m: ["child","11PM-1AM","first sign of Chinese zodiac","sign of the rat"] },
  { k: '外', n: 5, f: 81, r: ['がい', 'ガイ', 'げ', 'ゲ', 'そと', 'ソト', 'ほか'], m: ["outside"] },
  { k: '八', n: 5, f: 92, r: ['はち', 'ハチ', 'はつ', 'ハツ', 'や', 'ヤ', 'よう', 'ヨウ'], m: ["eight"] },
  { k: '六', n: 5, f: 93, r: ['りく', 'リク', 'ろく', 'ロク', 'む', 'ム', 'むい'], m: ["six"] },
  { k: '下', n: 5, f: 97, r: ['か', 'カ', 'げ', 'ゲ', 'した', 'シタ', 'しも', 'シモ', 'もと', 'モト'], m: ["below","descend","down","give","inferior","low"] },
  { k: '来', n: 5, f: 102, r: ['たい', 'タイ', 'らい', 'ライ', 'き', 'キ', 'こ', 'コ'], m: ["come","become","cause","due","next"] },
  { k: '気', n: 5, f: 113, r: ['き', 'キ', 'け', 'ケ'], m: ["spirit","air","atmosphere","mind","mood"] },
  { k: '小', n: 5, f: 114, r: ['しょう', 'ショウ'], m: ["little","small"] },
  { k: '七', n: 5, f: 115, r: ['しち', 'シチ', 'なな', 'ナナ', 'なの', 'ナノ'], m: ["seven"] },
  { k: '山', n: 5, f: 131, r: ['さん', 'サン', 'せん', 'セン', 'やま', 'ヤマ'], m: ["mountain"] },
  { k: '話', n: 5, f: 134, r: ['わ', 'ワ', 'はなし', 'ハナシ'], m: ["tale","talk"] },
  { k: '女', n: 5, f: 151, r: ['じょ', 'ジョ', 'にょ', 'にょう', 'おんな', 'オンナ', 'め', 'メ'], m: ["woman","female"] },
  { k: '北', n: 5, f: 153, r: ['ほく', 'きた', 'キタ'], m: ["north"] },
  { k: '午', n: 5, f: 154, r: ['ご', 'ゴ', 'うま', 'ウマ'], m: ["noon","11AM-1PM","seventh sign of Chinese zodiac","sign of the horse"] },
  { k: '百', n: 5, f: 163, r: ['ひゃく'], m: ["hundred"] },
  { k: '書', n: 5, f: 169, r: ['しょ', 'ショ'], m: ["write"] },
  { k: '先', n: 5, f: 173, r: ['せん', 'セン', 'さき', 'サキ'], m: ["before","ahead","future","precedence","previous"] },
  { k: '名', n: 5, f: 177, r: ['みょう', 'めい', 'メイ', 'な', 'ナ'], m: ["name","distinguished","noted","reputation"] },
  { k: '川', n: 5, f: 181, r: ['せん', 'セン', 'かわ'], m: ["stream","river"] },
  { k: '千', n: 5, f: 195, r: ['せん', 'セン', 'ち', 'チ'], m: ["thousand"] },
  { k: '水', n: 5, f: 223, r: ['すい', 'スイ', 'みず', 'ミズ'], m: ["water"] },
  { k: '半', n: 5, f: 224, r: ['はん', 'ハン'], m: ["half","middle","odd number","part-","semi-"] },
  { k: '男', n: 5, f: 240, r: ['だん', 'ダン', 'なん', 'ナン', 'お', 'オ', 'おとこ', 'オトコ'], m: ["male/man","male"] },
  { k: '西', n: 5, f: 259, r: ['さい', 'サイ', 'す', 'ス', 'せい', 'セイ', 'にし', 'ニシ'], m: ["west","Spain"] },
  { k: '電', n: 5, f: 268, r: ['でん', 'デン'], m: ["electricity"] },
  { k: '校', n: 5, f: 294, r: ['きょう', 'キョウ', 'こう', 'コウ'], m: ["exam","correction","printing","proof","school"] },
  { k: '語', n: 5, f: 301, r: ['ご', 'ゴ'], m: ["word","language","speech"] },
  { k: '土', n: 5, f: 307, r: ['と', 'ト', 'ど', 'ド', 'つち', 'ツチ'], m: ["soil","Turkey","earth","ground"] },
  { k: '木', n: 5, f: 317, r: ['ぼく', 'ボク', 'もく', 'モク', 'き', 'キ'], m: ["tree","wood"] },
  { k: '聞', n: 5, f: 319, r: ['ぶん', 'ブン', 'もん', 'モン'], m: ["hear","ask","listen"] },
  { k: '食', n: 5, f: 328, r: ['しょく', 'じき'], m: ["eat","food"] },
  { k: '車', n: 5, f: 333, r: ['しゃ', 'シャ', 'くるま', 'クルマ'], m: ["car"] },
  { k: '何', n: 5, f: 340, r: ['か', 'カ', 'なに', 'なん', 'ナン'], m: ["what"] },
  { k: '南', n: 5, f: 341, r: ['な', 'ナ', 'なん', 'ナン', 'みなみ', 'ミナミ'], m: ["south"] },
  { k: '万', n: 5, f: 375, r: ['ばん', 'バン', 'まん', 'マン', 'よろず'], m: ["ten thousand","10,000"] },
  { k: '毎', n: 5, f: 436, r: ['まい', 'マイ', 'ごと', 'ゴト'], m: ["every"] },
  { k: '白', n: 5, f: 483, r: ['はく', 'ハク', 'しろ', 'シロ'], m: ["white"] },
  { k: '天', n: 5, f: 512, r: ['てん', 'テン', 'あめ', 'アメ'], m: ["heavens","imperial","sky"] },
  { k: '母', n: 5, f: 570, r: ['ぼ', 'ボ', 'はは', 'ハハ', 'も', 'モ'], m: ["mama","mother"] },
  { k: '火', n: 5, f: 574, r: ['か', 'カ', 'ひ', 'ヒ'], m: ["fire"] },
  { k: '右', n: 5, f: 602, r: ['う', 'ウ', 'ゆう', 'ユウ', 'みぎ', 'ミギ'], m: ["right"] },
  { k: '読', n: 5, f: 618, r: ['とう', 'トウ', 'とく', 'トク', 'どく', 'ドク'], m: ["read"] },
  { k: '友', n: 5, f: 622, r: ['ゆう', 'ユウ', 'とも', 'トモ'], m: ["friend"] },
  { k: '左', n: 5, f: 630, r: ['さ', 'サ', 'しゃ', 'シャ', 'ひだり'], m: ["left"] },
  { k: '休', n: 5, f: 642, r: ['きゅう', 'キュウ'], m: ["rest","day off","retire","sleep"] },
  { k: '父', n: 5, f: 646, r: ['ふ', 'フ', 'ちち', 'チチ'], m: ["father"] },
  { k: '雨', n: 5, f: 950, r: ['う', 'ウ', 'あめ', 'アメ'], m: ["rain"] },
  { k: '会', n: 4, f: 4, r: ['え', 'エ', 'かい', 'カイ'], m: ["meeting","association","interview","join","meet","party"] },
  { k: '同', n: 4, f: 15, r: ['どう', 'ドウ'], m: ["same","agree","equal"] },
  { k: '事', n: 4, f: 18, r: ['じ', 'ジ', 'ず', 'ズ', 'こと', 'コト'], m: ["matter","business","fact","possibly","reason","thing"] },
  { k: '自', n: 4, f: 19, r: ['し', 'シ', 'じ', 'ジ'], m: ["oneself"] },
  { k: '社', n: 4, f: 21, r: ['しゃ', 'シャ', 'やしろ'], m: ["company","association","firm","office","shrine"] },
  { k: '発', n: 4, f: 32, r: ['はつ', 'ハツ'], m: ["discharge","counter for gunshots","departure","disclose","emit","publish","start from"] },
  { k: '者', n: 4, f: 38, r: ['しゃ', 'シャ', 'もの', 'モノ'], m: ["someone","person"] },
  { k: '地', n: 4, f: 40, r: ['じ', 'ジ', 'ち', 'チ'], m: ["ground","earth"] },
  { k: '業', n: 4, f: 43, r: ['ぎょう', 'ごう', 'ゴウ', 'わざ', 'ワザ'], m: ["business/profession","arts","business","performance","vocation"] },
  { k: '方', n: 4, f: 46, r: ['ほう', 'ホウ', 'かた', 'カタ'], m: ["direction","alternative","person"] },
  { k: '新', n: 4, f: 51, r: ['しん', 'シン'], m: ["new"] },
  { k: '場', n: 4, f: 52, r: ['じょう', 'ちょう', 'チョウ', 'ば', 'バ'], m: ["location","place"] },
  { k: '員', n: 4, f: 54, r: ['いん', 'イン'], m: ["employee","member","number","the one in charge"] },
  { k: '立', n: 4, f: 58, r: ['リットル', 'りつ', 'リツ', 'りゅう', 'リュウ'], m: ["stand up","erect","rise","set up"] },
  { k: '開', n: 4, f: 59, r: ['かい', 'カイ'], m: ["open","unfold","unseal"] },
  { k: '手', n: 4, f: 60, r: ['しゅ', 'シュ', 'ず', 'ズ', 'て', 'テ'], m: ["hand"] },
  { k: '力', n: 4, f: 62, r: ['りき', 'リキ', 'りょく', 'ちから', 'チカラ'], m: ["power","bear up","exert","strain","strength","strong"] },
  { k: '問', n: 4, f: 64, r: ['もん', 'モン', 'とん', 'トン'], m: ["question","ask","problem"] },
  { k: '代', n: 4, f: 66, r: ['たい', 'タイ', 'だい', 'ダイ', 'しろ', 'シロ', 'よ', 'ヨ'], m: ["substitute","age","change","charge","convert","counter for decades of ages, eras, etc.","fee","generation","period","rate","replace"] },
  { k: '明', n: 4, f: 67, r: ['みょう', 'みん', 'ミン', 'めい', 'メイ'], m: ["bright","light"] },
  { k: '動', n: 4, f: 73, r: ['どう', 'ドウ'], m: ["move","change","confusion","motion","shake","shift"] },
  { k: '京', n: 4, f: 74, r: ['きょう', 'キョウ', 'きん', 'キン', 'けい', 'ケイ', 'みやこ', 'ミヤコ'], m: ["capital","10**16"] },
  { k: '目', n: 4, f: 76, r: ['ぼく', 'ボク', 'もく', 'モク', 'め', 'メ'], m: ["eye","care","class","experience","favor","insight","look"] },
  { k: '通', n: 4, f: 80, r: ['つ', 'ツ', 'つう'], m: ["traffic","avenue","commute","counter for letters, notes, documents, etc.","pass through"] },
  { k: '言', n: 4, f: 83, r: ['げん', 'ゲン', 'ごん', 'ゴン', 'こと', 'コト'], m: ["say","word"] },
  { k: '理', n: 4, f: 86, r: ['り', 'リ', 'ことわり'], m: ["logic","arrangement","justice","reason","truth"] },
  { k: '体', n: 4, f: 88, r: ['たい', 'タイ', 'てい', 'テイ', 'かたち', 'カタチ', 'からだ', 'カラダ'], m: ["body","counter for images","object","reality","substance"] },
  { k: '田', n: 4, f: 90, r: ['でん', 'デン', 'た', 'タ'], m: ["rice field","rice paddy"] },
  { k: '主', n: 4, f: 95, r: ['しゅ', 'シュ', 'しゅう', 'シュウ', 'す', 'ス', 'あるじ', 'おも', 'ぬし', 'ヌシ'], m: ["lord","chief","main thing","master","principal"] },
  { k: '題', n: 4, f: 96, r: ['だい', 'ダイ'], m: ["topic","subject"] },
  { k: '意', n: 4, f: 99, r: ['い', 'イ'], m: ["idea","care","desire","heart","liking","mind","taste","thought"] },
  { k: '不', n: 4, f: 101, r: ['ふ', 'フ', 'ぶ', 'ブ'], m: ["negative","bad","clumsy","non-","ugly"] },
  { k: '作', n: 4, f: 103, r: ['さ', 'サ', 'さく', 'サク'], m: ["make","build","prepare","production"] },
  { k: '用', n: 4, f: 107, r: ['よう', 'ヨウ'], m: ["utilize","business","employ","service","use"] },
  { k: '度', n: 4, f: 110, r: ['たく', 'タク', 'と', 'ト', 'ど', 'ド', 'たび'], m: ["degrees","attitude","consider","counter for occurrences","occurrence","time"] },
  { k: '強', n: 4, f: 112, r: ['きょう', 'キョウ', 'ごう', 'ゴウ'], m: ["strong"] },
  { k: '公', n: 4, f: 118, r: ['く', 'ク', 'こう', 'コウ'], m: ["public","governmental","official","prince"] },
  { k: '持', n: 4, f: 119, r: ['じ', 'ジ'], m: ["hold","have"] },
  { k: '野', n: 4, f: 120, r: ['しょ', 'ショ', 'や', 'ヤ', 'の', 'ノ'], m: ["plains","civilian life","field","rustic"] },
  { k: '以', n: 4, f: 126, r: ['い', 'イ'], m: ["by means of","because","compared with","in view of"] },
  { k: '思', n: 4, f: 132, r: ['し', 'シ'], m: ["think"] },
  { k: '家', n: 4, f: 133, r: ['か', 'カ', 'け', 'ケ', 'いえ', 'イエ', 'うち', 'ウチ', 'や', 'ヤ'], m: ["house","expert","family","home","performer","professional"] },
  { k: '世', n: 4, f: 135, r: ['せ', 'セ', 'せい', 'セイ', 'そう', 'ソウ', 'よ', 'ヨ'], m: ["generation","public","society","world"] },
  { k: '多', n: 4, f: 139, r: ['た', 'タ'], m: ["many","frequent","much"] },
  { k: '正', n: 4, f: 143, r: ['しょう', 'ショウ', 'せい', 'セイ', 'まさ', 'マサ'], m: ["correct","10**40","justice","righteous"] },
  { k: '安', n: 4, f: 144, r: ['あん', 'アン', 'やす', 'ヤス'], m: ["relax","cheap","contented","low","peaceful","quiet","rested"] },
  { k: '院', n: 4, f: 150, r: ['いん', 'イン'], m: ["Inst.","institution","mansion","school","temple"] },
  { k: '心', n: 4, f: 157, r: ['しん', 'シン', 'こころ', 'ココロ'], m: ["heart","mind","spirit"] },
  { k: '界', n: 4, f: 158, r: ['かい', 'カイ'], m: ["world","boundary"] },
  { k: '教', n: 4, f: 166, r: ['きょう', 'キョウ'], m: ["teach","doctrine","faith"] },
  { k: '文', n: 4, f: 190, r: ['ぶん', 'ブン', 'もん', 'モン', 'あや', 'アヤ', 'ふみ', 'フミ'], m: ["sentence","art","decoration","figures","literature","plan","style"] },
  { k: '元', n: 4, f: 192, r: ['がん', 'ガン', 'げん', 'ゲン', 'もと', 'モト'], m: ["beginning","former time","origin"] },
  { k: '重', n: 4, f: 193, r: ['じゅう', 'ちょう', 'チョウ', 'え', 'エ', 'おも'], m: ["heavy","-fold","esteem","heap up","important","nest of boxes","pile up","respect"] },
  { k: '近', n: 4, f: 194, r: ['きん', 'キン', 'こん', 'コン'], m: ["near","akin","early","tantamount"] },
  { k: '考', n: 4, f: 196, r: ['こう', 'コウ'], m: ["consider","think over"] },
  { k: '画', n: 4, f: 199, r: ['え', 'エ', 'かい', 'カイ', 'かく', 'カク', 'が', 'ガ'], m: ["brush stroke","brush-stroke","picture"] },
  { k: '海', n: 4, f: 200, r: ['かい', 'カイ', 'うみ', 'ウミ'], m: ["sea","ocean"] },
  { k: '売', n: 4, f: 202, r: ['ばい', 'バイ'], m: ["sell"] },
  { k: '知', n: 4, f: 205, r: ['ち', 'チ'], m: ["know","wisdom"] },
  { k: '道', n: 4, f: 207, r: ['とう', 'トウ', 'どう', 'ドウ', 'いう', 'イウ', 'みち', 'ミチ'], m: ["road-way","course","district","journey","moral","street","teachings"] },
  { k: '集', n: 4, f: 210, r: ['しゅう', 'シュウ'], m: ["gather","congregate","flock","meet","swarm"] },
  { k: '別', n: 4, f: 214, r: ['べつ'], m: ["separate","another","branch off","diverge","extra","fork","specially"] },
  { k: '物', n: 4, f: 215, r: ['ぶつ', 'ブツ', 'もつ', 'モツ', 'もの', 'モノ'], m: ["thing","matter","object"] },
  { k: '使', n: 4, f: 219, r: ['し', 'シ'], m: ["use","ambassador","cause","envoy","messenger","order","send on a mission"] },
  { k: '品', n: 4, f: 225, r: ['ひん', 'ヒン', 'ほん', 'ホン', 'しな', 'シナ'], m: ["goods","article","counter for meal courses","dignity","refinement"] },
  { k: '計', n: 4, f: 228, r: ['けい', 'ケイ'], m: ["plot","measure","plan","scheme"] },
  { k: '死', n: 4, f: 229, r: ['し', 'シ'], m: ["death","die"] },
  { k: '特', n: 4, f: 234, r: ['とく', 'トク'], m: ["special"] },
  { k: '私', n: 4, f: 242, r: ['し', 'シ', 'わたくし', 'わたし', 'ワタシ'], m: ["private","I","me"] },
  { k: '始', n: 4, f: 244, r: ['し', 'シ'], m: ["commence","begin"] },
  { k: '朝', n: 4, f: 248, r: ['ちょう', 'チョウ', 'あさ', 'アサ'], m: ["morning","(North) Korea","dynasty","epoch","period","regime"] },
  { k: '運', n: 4, f: 255, r: ['うん', 'ウン'], m: ["carry","advance","destiny","fate","lot","luck","progress","transport"] },
  { k: '終', n: 4, f: 256, r: ['しゅう', 'シュウ', 'つい', 'ツイ'], m: ["end","finish"] },
  { k: '台', n: 4, f: 262, r: ['たい', 'タイ', 'だい', 'ダイ', 'ウテナ', 'つかさ', 'ツカサ', 'われ'], m: ["pedestal","a stand","counter for machines and vehicles"] },
  { k: '広', n: 4, f: 263, r: ['こう', 'コウ'], m: ["wide","broad","spacious"] },
  { k: '住', n: 4, f: 270, r: ['じゅう', 'ちゅう', 'チュウ'], m: ["dwell","inhabit","live","reside"] },
  { k: '真', n: 4, f: 279, r: ['しん', 'シン', 'ま', 'マ', 'まこと', 'マコト'], m: ["true","Buddhist sect","reality"] },
  { k: '有', n: 4, f: 282, r: ['う', 'ウ', 'ゆう', 'ユウ'], m: ["possess","approx","exist","happen","have","occur"] },
  { k: '口', n: 4, f: 284, r: ['く', 'ク', 'こう', 'コウ', 'くち'], m: ["mouth"] },
  { k: '少', n: 4, f: 287, r: ['しょう', 'ショウ'], m: ["few","little"] },
  { k: '町', n: 4, f: 292, r: ['ちょう', 'チョウ', 'まち', 'マチ'], m: ["village","block","street","town"] },
  { k: '料', n: 4, f: 295, r: ['りょう', 'リョウ'], m: ["fee","materials"] },
  { k: '工', n: 4, f: 299, r: ['く', 'ク', 'ぐ', 'グ', 'こう', 'コウ'], m: ["craft","construction"] },
  { k: '建', n: 4, f: 300, r: ['けん', 'ケン', 'こん', 'コン'], m: ["build"] },
  { k: '空', n: 4, f: 304, r: ['くう', 'クウ', 'から', 'カラ', 'そら', 'ソラ'], m: ["empty","sky","vacant","vacuum","void"] },
  { k: '急', n: 4, f: 309, r: ['きゅう', 'キュウ'], m: ["hurry","emergency","steep","sudden"] },
  { k: '止', n: 4, f: 310, r: ['し', 'シ'], m: ["stop","halt"] },
  { k: '送', n: 4, f: 311, r: ['そう', 'ソウ'], m: ["escort/send off","escort","send"] },
  { k: '切', n: 4, f: 324, r: ['さい', 'サイ', 'せつ', 'セツ'], m: ["cut","be sharp","cutoff"] },
  { k: '転', n: 4, f: 327, r: ['てん', 'テン'], m: ["revolve","change","turn around"] },
  { k: '研', n: 4, f: 336, r: ['けん', 'ケン'], m: ["polish","sharpen","study of"] },
  { k: '足', n: 4, f: 343, r: ['そく', 'ソク', 'あし', 'アシ'], m: ["leg","be sufficient","counter for pairs of footwear","foot"] },
  { k: '究', n: 4, f: 368, r: ['きゅう', 'キュウ', 'く', 'ク'], m: ["research","study"] },
  { k: '楽', n: 4, f: 373, r: ['がく', 'ガク', 'ごう', 'ゴウ', 'らく', 'ラク'], m: ["music","comfort","ease"] },
  { k: '起', n: 4, f: 374, r: ['き', 'キ'], m: ["rouse","get up","wake up"] },
  { k: '着', n: 4, f: 376, r: ['じゃく', 'ちゃく'], m: ["don","arrive","counter for suits of clothing","wear"] },
  { k: '店', n: 4, f: 378, r: ['てん', 'テン', 'たな', 'タナ', 'みせ', 'ミセ'], m: ["store","shop"] },
  { k: '病', n: 4, f: 384, r: ['びょう', 'へい', 'ヘイ', 'やまい'], m: ["ill","sick"] },
  { k: '質', n: 4, f: 389, r: ['しち', 'シチ', 'しつ', 'ち', 'チ', 'たち', 'タチ', 'もと', 'モト'], m: ["substance","matter","quality","temperament"] },
  { k: '待', n: 4, f: 391, r: ['たい', 'タイ'], m: ["wait","depend on"] },
  { k: '試', n: 4, f: 392, r: ['し', 'シ'], m: ["test","attempt","experiment","ordeal","try"] },
  { k: '族', n: 4, f: 393, r: ['ぞく'], m: ["tribe","family"] },
  { k: '銀', n: 4, f: 395, r: ['ぎん', 'ギン'], m: ["silver"] },
  { k: '早', n: 4, f: 402, r: ['そう', 'ソウ', 'はや', 'ハヤ'], m: ["early","fast"] },
  { k: '映', n: 4, f: 404, r: ['えい', 'エイ'], m: ["reflect","projection","reflection"] },
  { k: '親', n: 4, f: 406, r: ['しん', 'シン', 'おや', 'オヤ'], m: ["parent","dealer (cards)","familiarity","intimacy","relative"] },
  { k: '験', n: 4, f: 410, r: ['けん', 'ケン', 'げん', 'ゲン', 'あかし', 'しるし', 'ためし'], m: ["verification","effect","testing"] },
  { k: '英', n: 4, f: 430, r: ['えい', 'エイ'], m: ["England","English","calyx","hero","outstanding"] },
  { k: '医', n: 4, f: 437, r: ['い', 'イ'], m: ["doctor","medicine"] },
  { k: '仕', n: 4, f: 439, r: ['し', 'シ', 'じ', 'ジ'], m: ["attend","doing","official","serve"] },
  { k: '去', n: 4, f: 440, r: ['きょ', 'こ', 'コ'], m: ["gone","divorce","elapse","eliminate","leave","past","quit"] },
  { k: '味', n: 4, f: 442, r: ['み', 'ミ', 'あじ', 'アジ'], m: ["flavor","taste"] },
  { k: '写', n: 4, f: 453, r: ['しゃ', 'シャ', 'じゃ', 'ジャ'], m: ["copy","be photographed","describe"] },
  { k: '字', n: 4, f: 485, r: ['じ', 'ジ', 'あざ', 'アザ'], m: ["character","letter","section of village","word"] },
  { k: '答', n: 4, f: 486, r: ['とう', 'トウ'], m: ["solution","answer"] },
  { k: '夜', n: 4, f: 487, r: ['や', 'ヤ', 'よ', 'ヨ', 'よる'], m: ["night","evening"] },
  { k: '音', n: 4, f: 491, r: ['いん', 'イン', 'おん', 'オン', 'おと', 'オト', 'ね', 'ネ'], m: ["sound","noise"] },
  { k: '注', n: 4, f: 497, r: ['ちゅう', 'チュウ'], m: ["pour","annotate","comment","concentrate on","flow into","irrigate","notes","shed (tears)"] },
  { k: '帰', n: 4, f: 504, r: ['き', 'キ'], m: ["homecoming","arrive at","lead to","result in"] },
  { k: '古', n: 4, f: 509, r: ['こ', 'コ'], m: ["old"] },
  { k: '歌', n: 4, f: 519, r: ['か', 'カ', 'うた', 'ウタ'], m: ["song","sing"] },
  { k: '買', n: 4, f: 520, r: ['ばい', 'バイ'], m: ["buy"] },
  { k: '悪', n: 4, f: 530, r: ['あく', 'アク', 'お', 'オ', 'ああ', 'アア'], m: ["bad","evil","false","rascal","vice","wrong"] },
  { k: '図', n: 4, f: 539, r: ['ず', 'ズ', 'と', 'ト', 'え', 'エ'], m: ["map","audacious","drawing","extraordinary","plan"] },
  { k: '週', n: 4, f: 540, r: ['しゅう', 'シュウ'], m: ["week"] },
  { k: '室', n: 4, f: 550, r: ['しつ', 'むろ', 'ムロ'], m: ["room","apartment","cellar","chamber","greenhouse"] },
  { k: '歩', n: 4, f: 554, r: ['ふ', 'フ', 'ぶ', 'ブ', 'ほ', 'ホ'], m: ["walk","counter for steps"] },
  { k: '風', n: 4, f: 558, r: ['ふ', 'フ', 'ふう', 'フウ', 'かぜ', 'カゼ'], m: ["wind","air","manner","style"] },
  { k: '紙', n: 4, f: 559, r: ['し', 'シ', 'かみ', 'カミ'], m: ["paper"] },
  { k: '黒', n: 4, f: 573, r: ['こく', 'コク', 'くろ', 'クロ'], m: ["black"] },
  { k: '花', n: 4, f: 578, r: ['か', 'カ', 'け', 'ケ', 'はな', 'ハナ'], m: ["flower"] },
  { k: '春', n: 4, f: 579, r: ['しゅん', 'シュン', 'はる', 'ハル'], m: ["springtime","spring (season)"] },
  { k: '赤', n: 4, f: 584, r: ['しゃく', 'シャク', 'せき', 'セキ', 'あか', 'アカ'], m: ["red"] },
  { k: '青', n: 4, f: 589, r: ['しょう', 'ショウ', 'せい', 'セイ', 'あお', 'アオ'], m: ["blue","green"] },
  { k: '館', n: 4, f: 613, r: ['かん', 'カン', 'たて', 'タテ', 'やかた'], m: ["Bldg.","building","large building","mansion","palace"] },
  { k: '屋', n: 4, f: 616, r: ['おく', 'オク', 'や', 'ヤ'], m: ["roof","dealer","house","seller","shop"] },
  { k: '色', n: 4, f: 621, r: ['しき', 'シキ', 'しょく', 'いろ', 'イロ'], m: ["color"] },
  { k: '走', n: 4, f: 626, r: ['そう', 'ソウ'], m: ["run"] },
  { k: '秋', n: 4, f: 635, r: ['しゅう', 'シュウ', 'あき', 'アキ', 'とき', 'トキ'], m: ["autumn"] },
  { k: '夏', n: 4, f: 659, r: ['か', 'カ', 'が', 'ガ', 'げ', 'ゲ', 'なつ', 'ナツ'], m: ["summer"] },
  { k: '習', n: 4, f: 706, r: ['しゅう', 'シュウ', 'じゅ', 'ジュ'], m: ["learn"] },
  { k: '駅', n: 4, f: 724, r: ['えき'], m: ["station"] },
  { k: '洋', n: 4, f: 763, r: ['よう', 'ヨウ'], m: ["ocean","Western style","foreign","sea"] },
  { k: '旅', n: 4, f: 783, r: ['りょ', 'たび'], m: ["trip","travel"] },
  { k: '服', n: 4, f: 873, r: ['ふく', 'フク'], m: ["clothing","admit","discharge","obey"] },
  { k: '夕', n: 4, f: 924, r: ['せき', 'セキ', 'ゆう', 'ユウ'], m: ["evening"] },
  { k: '借', n: 4, f: 932, r: ['しゃく', 'シャク'], m: ["borrow","rent"] },
  { k: '曜', n: 4, f: 940, r: ['よう', 'ヨウ'], m: ["weekday"] },
  { k: '飲', n: 4, f: 969, r: ['いん', 'イン', 'おん', 'オン'], m: ["drink","smoke","take"] },
  { k: '肉', n: 4, f: 986, r: ['にく', 'ニク', 'しし', 'シシ'], m: ["meat"] },
  { k: '貸', n: 4, f: 995, r: ['たい', 'タイ'], m: ["lend"] },
  { k: '堂', n: 4, f: 1010, r: ['どう', 'ドウ'], m: ["public chamber/hall","hall","public chamber"] },
  { k: '鳥', n: 4, f: 1043, r: ['ちょう', 'チョウ', 'とり', 'トリ'], m: ["bird","chicken"] },
  { k: '飯', n: 4, f: 1046, r: ['はん', 'ハン', 'めし', 'メシ'], m: ["meal","boiled rice"] },
  { k: '勉', n: 4, f: 1066, r: ['べん', 'ベン'], m: ["exertion","diligent","encourage","endeavour","make effort","strive"] },
  { k: '冬', n: 4, f: 1090, r: ['とう', 'トウ', 'ふゆ', 'フユ'], m: ["winter"] },
  { k: '昼', n: 4, f: 1115, r: ['ちゅう', 'チュウ', 'ひる', 'ヒル'], m: ["daytime","noon"] },
  { k: '茶', n: 4, f: 1116, r: ['さ', 'サ', 'ちゃ', 'チャ'], m: ["tea"] },
  { k: '弟', n: 4, f: 1161, r: ['だい', 'ダイ', 'てい', 'テイ', 'で', 'デ', 'おとうと'], m: ["younger brother","faithful service to elders"] },
  { k: '牛', n: 4, f: 1202, r: ['ぎゅう', 'うし', 'ウシ'], m: ["cow"] },
  { k: '魚', n: 4, f: 1208, r: ['ぎょ', 'ギョ', 'うお', 'ウオ', 'さかな', 'サカナ'], m: ["fish"] },
  { k: '兄', n: 4, f: 1219, r: ['きょう', 'キョウ', 'けい', 'ケイ', 'あに', 'アニ'], m: ["elder brother","big brother"] },
  { k: '犬', n: 4, f: 1326, r: ['けん', 'ケン', 'いぬ', 'イヌ'], m: ["dog"] },
  { k: '妹', n: 4, f: 1446, r: ['まい', 'マイ', 'いもうと'], m: ["younger sister"] },
  { k: '姉', n: 4, f: 1473, r: ['し', 'シ', 'あね', 'はは', 'ハハ'], m: ["elder sister"] },
  { k: '漢', n: 4, f: 1487, r: ['かん', 'カン'], m: ["Sino-","China"] },
  { k: '政', n: 3, f: 17, r: ['しょう', 'ショウ', 'せい', 'セイ'], m: ["politics","government"] },
  { k: '議', n: 3, f: 25, r: ['ぎ', 'ギ'], m: ["deliberation","consideration","consultation","debate"] },
  { k: '民', n: 3, f: 28, r: ['みん', 'ミン', 'たみ', 'タミ'], m: ["people","nation","subjects"] },
  { k: '連', n: 3, f: 30, r: ['れん', 'レン'], m: ["take along","clique","connect","gang","join","lead","party"] },
  { k: '対', n: 3, f: 34, r: ['たい', 'タイ', 'つい', 'ツイ', 'あいて', 'アイテ'], m: ["vis-a-vis","anti-","compare","equal","even","opposite","versus"] },
  { k: '部', n: 3, f: 36, r: ['ぶ', 'ブ'], m: ["section","bureau","class","copy","counter for copies of a newspaper or magazine","dept","part","portion"] },
  { k: '合', n: 3, f: 41, r: ['ごう', 'ゴウ'], m: ["fit","0.1","join","suit"] },
  { k: '市', n: 3, f: 42, r: ['し', 'シ', 'いち', 'イチ'], m: ["market","city","town"] },
  { k: '内', n: 3, f: 44, r: ['だい', 'ダイ', 'ない', 'ナイ', 'うち', 'ウチ'], m: ["inside","among","between","home","house","within"] },
  { k: '相', n: 3, f: 45, r: ['しょう', 'ショウ', 'そう', 'ソウ'], m: ["inter-","aspect","councillor","each other","minister of state","mutual","phase","physiognomy","together"] },
  { k: '定', n: 3, f: 48, r: ['じょう', 'てい', 'テイ'], m: ["determine","decide","establish","fix"] },
  { k: '回', n: 3, f: 50, r: ['え', 'エ', 'かい', 'カイ'], m: ["-times","counter for occurrences","game","revolve","round"] },
  { k: '選', n: 3, f: 57, r: ['せん', 'セン'], m: ["elect","choose","prefer","select"] },
  { k: '米', n: 3, f: 61, r: ['ベイ', 'まい', 'マイ', 'こめ', 'コメ', 'よね', 'ヨネ'], m: ["rice","USA","metre"] },
  { k: '実', n: 3, f: 68, r: ['しつ', 'じつ', 'まこと', 'マコト', 'み', 'ミ', 'みの', 'ミノ'], m: ["reality","fruit","nut","seed","truth"] },
  { k: '関', n: 3, f: 70, r: ['かん', 'カン', 'からくり', 'カラクリ', 'せき', 'セキ'], m: ["connection","barrier","concerning","gateway","involve"] },
  { k: '決', n: 3, f: 71, r: ['けつ'], m: ["decide","agree upon","appoint","fix"] },
  { k: '全', n: 3, f: 75, r: ['ぜん', 'ゼン'], m: ["whole","all","complete","entire","fulfill"] },
  { k: '表', n: 3, f: 77, r: ['ひょう', 'ヒョウ'], m: ["surface","chart","diagram","table"] },
  { k: '戦', n: 3, f: 78, r: ['せん', 'セン', 'いくさ', 'イクサ'], m: ["war","battle","match"] },
  { k: '経', n: 3, f: 79, r: ['きょう', 'キョウ', 'きん', 'キン', 'けい', 'ケイ', 'のり', 'ノリ'], m: ["sutra","expire","longitude","pass thru","warp"] },
  { k: '最', n: 3, f: 82, r: ['さい', 'サイ', 'しゅ', 'シュ', 'つま'], m: ["utmost","extreme","most"] },
  { k: '現', n: 3, f: 85, r: ['げん', 'ゲン', 'うつつ'], m: ["present","actual","existing"] },
  { k: '調', n: 3, f: 87, r: ['ちょう', 'チョウ'], m: ["tune","exorcise","harmonize","investigate","key (music)","mediate","meter","prepare","tone","writing style"] },
  { k: '化', n: 3, f: 89, r: ['か', 'カ', 'け', 'ケ'], m: ["change","-ization","delude","enchant","influence","take the form of"] },
  { k: '当', n: 3, f: 91, r: ['とう', 'トウ'], m: ["hit","appropriate","himself","right"] },
  { k: '約', n: 3, f: 94, r: ['やく', 'ヤク'], m: ["promise","approximately","shrink"] },
  { k: '首', n: 3, f: 98, r: ['しゅ', 'シュ', 'くび', 'クビ'], m: ["neck","counter for songs and poems"] },
  { k: '法', n: 3, f: 100, r: ['ふらん', 'フラン', 'ほう', 'ホウ', 'のり', 'ノリ'], m: ["method","law","model","principle","rule","system"] },
  { k: '性', n: 3, f: 104, r: ['しょう', 'ショウ', 'せい', 'セイ', 'さが', 'サガ'], m: ["sex","gender","nature"] },
  { k: '要', n: 3, f: 106, r: ['よう', 'ヨウ', 'かなめ', 'カナメ'], m: ["need","essence","key to","main point","pivot"] },
  { k: '制', n: 3, f: 108, r: ['せい', 'セイ'], m: ["system","law","rule"] },
  { k: '治', n: 3, f: 109, r: ['じ', 'ジ', 'ち', 'チ'], m: ["reign","be at peace","calm down","conserve","cure","govt","heal","quell","rule","subdue"] },
  { k: '務', n: 3, f: 111, r: ['む', 'ム'], m: ["task","duties"] },
  { k: '成', n: 3, f: 116, r: ['じょう', 'せい', 'セイ'], m: ["turn into","become","elapse","get","grow","reach"] },
  { k: '期', n: 3, f: 117, r: ['き', 'キ', 'ご', 'ゴ'], m: ["period","date","term","time"] },
  { k: '取', n: 3, f: 122, r: ['しゅ', 'シュ', 'とり', 'トリ'], m: ["take","fetch","take up"] },
  { k: '都', n: 3, f: 123, r: ['つ', 'ツ', 'と', 'ト', 'みやこ', 'ミヤコ'], m: ["metropolis","all","capital","everything"] },
  { k: '和', n: 3, f: 124, r: ['お', 'オ', 'か', 'カ', 'わ', 'ワ'], m: ["harmony","Japan","Japanese style","peace","soften"] },
  { k: '機', n: 3, f: 127, r: ['き', 'キ', 'はた', 'ハタ'], m: ["mechanism","airplane","efficacy","loom","machine","occasion","opportunity","potency"] },
  { k: '平', n: 3, f: 128, r: ['ひょう', 'ヒョウ', 'びょう', 'へい', 'ヘイ', 'ひら', 'ヒラ'], m: ["even","flat","peace"] },
  { k: '加', n: 3, f: 130, r: ['か', 'カ'], m: ["add","Canada","addition","include","increase","join"] },
  { k: '受', n: 3, f: 136, r: ['じゅ', 'ジュ'], m: ["accept","answer (phone)","catch","get","receive","take","undergo"] },
  { k: '続', n: 3, f: 141, r: ['きょう', 'キョウ', 'こう', 'コウ', 'しょく', 'ぞく'], m: ["continue","sequel","series"] },
  { k: '進', n: 3, f: 142, r: ['しん', 'シン'], m: ["advance","proceed","progress","promote"] },
  { k: '数', n: 3, f: 148, r: ['さく', 'サク', 'しゅ', 'シュ', 'す', 'ス', 'すう', 'そく', 'ソク', 'かず', 'カズ', 'しばしば'], m: ["number","fate","figures","law","strength"] },
  { k: '記', n: 3, f: 149, r: ['き', 'キ'], m: ["scribe","account","narrative"] },
  { k: '初', n: 3, f: 152, r: ['しょ', 'ショ', 'はつ', 'ハツ'], m: ["first time","beginning"] },
  { k: '指', n: 3, f: 155, r: ['し', 'シ', 'ユビ'], m: ["finger","indicate","measure (ruler)","play (chess)","point to","put into"] },
  { k: '権', n: 3, f: 156, r: ['けん', 'ケン', 'ごん', 'ゴン', 'おもり', 'オモリ', 'かり', 'カリ'], m: ["authority","power","rights"] },
  { k: '支', n: 3, f: 159, r: ['し', 'シ'], m: ["branch","support","sustain"] },
  { k: '産', n: 3, f: 161, r: ['さん', 'サン'], m: ["products","bear","childbirth","give birth","native","property","yield"] },
  { k: '点', n: 3, f: 165, r: ['てん', 'テン', 'ぼち'], m: ["spot","decimal point","mark","point","speck"] },
  { k: '報', n: 3, f: 167, r: ['ほう', 'ホウ'], m: ["report","news","retribution","reward"] },
  { k: '済', n: 3, f: 168, r: ['さい', 'サイ', 'せい', 'セイ'], m: ["finish","come to an end","excusable","need not","relieve (burden)","settle (debt, etc.)"] },
  { k: '活', n: 3, f: 171, r: ['かつ', 'カツ'], m: ["lively","being helped","living","resuscitation"] },
  { k: '原', n: 3, f: 172, r: ['げん', 'ゲン', 'はら', 'ハラ'], m: ["meadow","field","original","plain","prairie","primitive","tundra","wilderness"] },
  { k: '共', n: 3, f: 174, r: ['きょう', 'キョウ', 'とも', 'トモ'], m: ["together","alike","all","and","both","neither","with"] },
  { k: '得', n: 3, f: 175, r: ['とく', 'トク'], m: ["gain","able to","acquire","advantage","benefit","can","earn","find","get","may","profit"] },
  { k: '解', n: 3, f: 176, r: ['かい', 'カイ', 'げ', 'ゲ'], m: ["unravel","absolve","answer","cancel","explain","explanation","key","minute","notes","solve","understanding","undo","untie"] },
  { k: '交', n: 3, f: 178, r: ['こう', 'コウ', 'こもごも'], m: ["mingle","association","coming & going","mixing"] },
  { k: '資', n: 3, f: 179, r: ['し', 'シ'], m: ["assets","be conducive to","capital","contribute to","data","funds","resources"] },
  { k: '予', n: 3, f: 180, r: ['しゃ', 'シャ', 'よ', 'ヨ'], m: ["beforehand","I","myself","previous"] },
  { k: '向', n: 3, f: 182, r: ['こう', 'コウ', 'むこ', 'ムコ'], m: ["yonder","approach","beyond","confront","defy","facing","tend toward"] },
  { k: '際', n: 3, f: 183, r: ['さい', 'サイ', 'きわ', 'キワ'], m: ["occasion","adventurous","dangerous","edge","indecent","side","time","verge","when"] },
  { k: '勝', n: 3, f: 185, r: ['しょう', 'ショウ', 'かつ', 'カツ'], m: ["victory","excel","prevail","win"] },
  { k: '面', n: 3, f: 186, r: ['べん', 'ベン', 'めん', 'メン', 'おも', 'つら'], m: ["mask","face","features","surface"] },
  { k: '告', n: 3, f: 188, r: ['こく', 'コク'], m: ["revelation","announce","inform","tell"] },
  { k: '反', n: 3, f: 191, r: ['たん', 'タン', 'はん', 'ハン', 'ほ', 'ホ', 'ほん', 'ホン'], m: ["anti-"] },
  { k: '判', n: 3, f: 197, r: ['はん', 'ハン', 'ばん', 'バン'], m: ["judgment","judgement","seal","signature","stamp"] },
  { k: '認', n: 3, f: 198, r: ['にん', 'ニン'], m: ["acknowledge","appreciate","believe","discern","recognize","witness"] },
  { k: '参', n: 3, f: 201, r: ['さん', 'サン', 'しん', 'シン', 'みつ', 'ミツ'], m: ["nonplussed/visit","be defeated","be madly in love","coming","die","going","nonplussed","participate","take part in","three (in documents)","visit","visiting"] },
  { k: '利', n: 3, f: 203, r: ['り', 'リ'], m: ["profit","advantage","benefit"] },
  { k: '組', n: 3, f: 204, r: ['そ', 'ソ', 'くみ', 'クミ'], m: ["association","assemble","braid","construct","cooperate","grapple","plait","unite"] },
  { k: '信', n: 3, f: 208, r: ['しん', 'シン'], m: ["faith","fidelity","trust","truth"] },
  { k: '在', n: 3, f: 211, r: ['ざい'], m: ["exist","located in","outskirts","suburbs"] },
  { k: '件', n: 3, f: 212, r: ['けん', 'ケン', 'くだん'], m: ["affair","case","item","matter"] },
  { k: '側', n: 3, f: 216, r: ['そく', 'ソク', 'かわ', 'がわ', 'ガワ', 'そば', 'ソバ'], m: ["side","lean","oppose","regret"] },
  { k: '任', n: 3, f: 217, r: ['にん', 'ニン'], m: ["responsibility","appoint","duty","entrust to","term"] },
  { k: '引', n: 3, f: 218, r: ['いん', 'イン'], m: ["pull","admit","install","jerk","quote","refer to","tug"] },
  { k: '求', n: 3, f: 220, r: ['きゅう', 'キュウ', 'ぐ', 'グ'], m: ["request","demand","require","want","wish for"] },
  { k: '所', n: 3, f: 221, r: ['しょ', 'ショ', 'とこ', 'トコ', 'ところ', 'トコロ', 'どころ'], m: ["place","extent"] },
  { k: '次', n: 3, f: 222, r: ['し', 'シ', 'じ', 'ジ', 'つぎ'], m: ["next","order","sequence"] },
  { k: '昨', n: 3, f: 226, r: ['さく', 'サク'], m: ["yesterday","previous"] },
  { k: '論', n: 3, f: 227, r: ['ろん', 'ロン'], m: ["argument","discourse"] },
  { k: '官', n: 3, f: 230, r: ['かん', 'カン'], m: ["bureaucrat","organ","the government"] },
  { k: '増', n: 3, f: 231, r: ['ぞう', 'ゾウ'], m: ["increase","add","augment","gain","promote"] },
  { k: '係', n: 3, f: 232, r: ['けい', 'ケイ', 'かかり'], m: ["person in charge","concern oneself","connection","duty"] },
  { k: '感', n: 3, f: 233, r: ['かん', 'カン'], m: ["emotion","feeling","sensation"] },
  { k: '情', n: 3, f: 235, r: ['じょう', 'せい', 'セイ'], m: ["feelings","circumstances","emotion","facts","passion","sympathy"] },
  { k: '投', n: 3, f: 236, r: ['とう', 'トウ'], m: ["throw","abandon","discard","give up","hurl","invest in","join","launch into","sell at a loss"] },
  { k: '示', n: 3, f: 237, r: ['し', 'シ', 'じ', 'ジ'], m: ["show","display","express","indicate","point out"] },
  { k: '変', n: 3, f: 238, r: ['へん', 'ヘン'], m: ["unusual","change","strange"] },
  { k: '打', n: 3, f: 239, r: ['だ', 'ダ', 'ダース'], m: ["strike","dozen","hit","knock","pound"] },
  { k: '直', n: 3, f: 246, r: ['じか', 'ジカ', 'じき', 'ちょく'], m: ["straightaway","fix","frankness","honesty","repair"] },
  { k: '両', n: 3, f: 247, r: ['りょう', 'リョウ', 'てる', 'テル', 'ふたつ'], m: ["both","counter for carriages (e.g., in a train)","old Japanese coin","two"] },
  { k: '式', n: 3, f: 251, r: ['しき', 'シキ'], m: ["style","ceremony","expression","form","function","method","rite","system"] },
  { k: '確', n: 3, f: 252, r: ['かく', 'カク', 'こう', 'コウ'], m: ["assurance","clear","confirm","evident","firm","hard","solid","tight"] },
  { k: '果', n: 3, f: 258, r: ['か', 'カ'], m: ["fruit","achieve","carry out","complete","end","finish","reward","succeed"] },
  { k: '容', n: 3, f: 264, r: ['よう', 'ヨウ'], m: ["contain","form","looks"] },
  { k: '必', n: 3, f: 265, r: ['ひつ'], m: ["invariably","certain","inevitable"] },
  { k: '演', n: 3, f: 267, r: ['えん', 'エン'], m: ["performance","act","play","render","stage"] },
  { k: '歳', n: 3, f: 269, r: ['さい', 'サイ', 'せい', 'セイ', 'とし', 'トシ', 'とせ', 'よわい'], m: ["year-end","age","occasion","opportunity"] },
  { k: '争', n: 3, f: 271, r: ['そう', 'ソウ'], m: ["contend","argue","dispute"] },
  { k: '談', n: 3, f: 272, r: ['だん', 'ダン'], m: ["discuss","talk"] },
  { k: '能', n: 3, f: 273, r: ['のう', 'ノウ'], m: ["ability","capacity","skill","talent"] },
  { k: '位', n: 3, f: 276, r: ['い', 'イ', 'くらい', 'クライ', 'ぐらい'], m: ["rank","about","crown","grade","some","throne"] },
  { k: '置', n: 3, f: 277, r: ['ち', 'チ'], m: ["placement","deposit","employ","keep","leave behind","pawn","put","set"] },
  { k: '流', n: 3, f: 280, r: ['りゅう', 'リュウ', 'る', 'ル'], m: ["current","a sink","flow","forfeit"] },
  { k: '格', n: 3, f: 281, r: ['かく', 'カク', 'きゃく', 'こう', 'コウ', 'ごう', 'ゴウ'], m: ["status","capacity","case (law, grammar)","character","rank"] },
  { k: '疑', n: 3, f: 283, r: ['ぎ', 'ギ'], m: ["doubt","be suspicious","distrust","question"] },
  { k: '過', n: 3, f: 285, r: ['か', 'カ'], m: ["overdo","error","exceed","go beyond"] },
  { k: '局', n: 3, f: 286, r: ['きょく'], m: ["bureau","affair","board","conclusion","court lady","her apartment","lady-in-waiting","office"] },
  { k: '放', n: 3, f: 288, r: ['ほう', 'ホウ'], m: ["set free","banish","emit","fire","liberate","release","shoot"] },
  { k: '常', n: 3, f: 293, r: ['じょう', 'つね', 'ツネ'], m: ["usual","always","common","continually","long-lasting","normal","ordinary","regular"] },
  { k: '状', n: 3, f: 298, r: ['じょう'], m: ["status quo","appearance","circumstances","conditions","form"] },
  { k: '球', n: 3, f: 302, r: ['きゅう', 'キュウ', 'たま', 'タマ'], m: ["ball","sphere"] },
  { k: '職', n: 3, f: 305, r: ['しょく', 'そく', 'ソク'], m: ["post","employment","work"] },
  { k: '与', n: 3, f: 308, r: ['よ', 'ヨ', 'ともに'], m: ["bestow","award","cause","gift","give","godsend","impart","participate in","provide"] },
  { k: '供', n: 3, f: 313, r: ['きょう', 'キョウ', 'く', 'ク', 'くう', 'クウ', 'ぐ', 'グ', 'とも', 'トモ'], m: ["submit","accompany","offer","present","serve (meal)"] },
  { k: '役', n: 3, f: 315, r: ['えき', 'やく', 'ヤク'], m: ["duty","campaign","drafted labor","office","role","service","war"] },
  { k: '構', n: 3, f: 316, r: ['こう', 'コウ'], m: ["posture","appearance","build","set up","stance"] },
  { k: '割', n: 3, f: 318, r: ['かつ', 'カツ', 'わり', 'ワリ'], m: ["proportion","comparatively","cut","divide","separate","split"] },
  { k: '費', n: 3, f: 321, r: ['ひ', 'ヒ'], m: ["expense","consume","cost","spend","waste"] },
  { k: '付', n: 3, f: 322, r: ['ふ', 'フ'], m: ["adhere","append","attach","refer to"] },
  { k: '由', n: 3, f: 325, r: ['ゆ', 'ユ', 'ゆい', 'ユイ', 'ゆう', 'ユウ', 'よし', 'ヨシ'], m: ["wherefore","a reason"] },
  { k: '説', n: 3, f: 326, r: ['せつ', 'セツ', 'ぜい', 'ゼイ'], m: ["rumor/explanation","explanation","opinion","rumor","theory"] },
  { k: '難', n: 3, f: 330, r: ['なん', 'ナン'], m: ["difficult","accident","defect","impossible","trouble"] },
  { k: '優', n: 3, f: 334, r: ['う', 'ウ', 'ゆう', 'ユウ'], m: ["tenderness","actor","excel","gentleness","superiority","surpass"] },
  { k: '夫', n: 3, f: 335, r: ['ふ', 'フ', 'ふう', 'フウ', 'ぶ', 'ブ', 'おっと', 'オット', 'それ', 'ソレ'], m: ["husband","man"] },
  { k: '収', n: 3, f: 337, r: ['しゅう', 'シュウ'], m: ["income","obtain","pay","reap","store","supply"] },
  { k: '断', n: 3, f: 338, r: ['だん', 'ダン'], m: ["severance","apologize","cutting","decision","decline","dismiss","judgement","prohibit","refuse","warn"] },
  { k: '石', n: 3, f: 342, r: ['こく', 'コク', 'しゃく', 'シャク', 'せき', 'セキ', 'いし', 'イシ'], m: ["stone"] },
  { k: '違', n: 3, f: 344, r: ['い', 'イ'], m: ["difference","differ"] },
  { k: '消', n: 3, f: 345, r: ['しょう', 'ショウ'], m: ["extinguish","blow out","cancel","neutralize","turn off"] },
  { k: '神', n: 3, f: 347, r: ['しん', 'シン', 'じん', 'ジン', 'かみ', 'カミ'], m: ["gods","mind","soul"] },
  { k: '番', n: 3, f: 348, r: ['ばん', 'バン'], m: ["turn","number in a series"] },
  { k: '規', n: 3, f: 349, r: ['き', 'キ'], m: ["standard","measure"] },
  { k: '術', n: 3, f: 350, r: ['じゅつ', 'すべ'], m: ["art","magic","means","resources","skill","technique","trick"] },
  { k: '備', n: 3, f: 356, r: ['び', 'ビ'], m: ["equip","preparation","provision"] },
  { k: '宅', n: 3, f: 357, r: ['たく', 'タク'], m: ["home","house","my husband","our house","residence"] },
  { k: '害', n: 3, f: 358, r: ['がい', 'ガイ'], m: ["harm","injury"] },
  { k: '配', n: 3, f: 359, r: ['はい', 'ハイ'], m: ["distribute","exile","rationing","spouse"] },
  { k: '警', n: 3, f: 366, r: ['けい', 'ケイ'], m: ["admonish","commandment"] },
  { k: '育', n: 3, f: 369, r: ['いく', 'イク'], m: ["bring up","grow up","raise","rear"] },
  { k: '席', n: 3, f: 370, r: ['せき', 'セキ', 'むしろ'], m: ["seat","mat","occasion","place"] },
  { k: '訪', n: 3, f: 372, r: ['ほう', 'ホウ'], m: ["call on","look up","offer sympathy","visit"] },
  { k: '乗', n: 3, f: 377, r: ['しょう', 'ショウ', 'じょう'], m: ["ride","board","counter for vehicles","join","mount","multiplication","power","record"] },
  { k: '残', n: 3, f: 380, r: ['さん', 'サン', 'ざん', 'ザン'], m: ["remainder","balance","leftover"] },
  { k: '想', n: 3, f: 381, r: ['そ', 'ソ', 'そう', 'ソウ'], m: ["concept","idea","think","thought"] },
  { k: '声', n: 3, f: 388, r: ['しょう', 'ショウ', 'せい', 'セイ', 'こえ'], m: ["voice"] },
  { k: '念', n: 3, f: 390, r: ['ねん', 'ネン'], m: ["wish","attention","desire","feeling","idea","sense","thought"] },
  { k: '助', n: 3, f: 397, r: ['じょ', 'ジョ', 'すけ'], m: ["help","assist","rescue"] },
  { k: '労', n: 3, f: 398, r: ['ろう', 'ロウ'], m: ["labor","reward for","thank for","toil","trouble"] },
  { k: '例', n: 3, f: 399, r: ['れい', 'レイ'], m: ["example","custom","precedent","usage"] },
  { k: '然', n: 3, f: 401, r: ['ぜん', 'ゼン', 'ねん', 'ネン', 'さ', 'サ', 'しか', 'シカ'], m: ["sort of thing","if so","in that case","so","well"] },
  { k: '限', n: 3, f: 405, r: ['げん', 'ゲン'], m: ["limit","restrict","to best of ability"] },
  { k: '追', n: 3, f: 411, r: ['つい', 'ツイ'], m: ["chase","drive away","follow","meanwhile","pursue"] },
  { k: '商', n: 3, f: 413, r: ['しょう', 'ショウ'], m: ["make a deal","dealing in","merchant","selling"] },
  { k: '葉', n: 3, f: 414, r: ['よう', 'ヨウ', 'は', 'ハ'], m: ["leaf","blade","counter for flat things","fragment","lobe","needle","piece","plane","spear"] },
  { k: '伝', n: 3, f: 416, r: ['てん', 'テン', 'でん', 'デン', 'つて'], m: ["transmit","communicate","follow","go along","legend","report","tradition","walk along"] },
  { k: '働', n: 3, f: 417, r: ['どう', 'ドウ'], m: ["work","(kokuji)"] },
  { k: '形', n: 3, f: 418, r: ['ぎょう', 'けい', 'ケイ', 'かた', 'カタ', 'かたち', 'カタチ', 'なり', 'ナリ'], m: ["shape","form","style"] },
  { k: '景', n: 3, f: 419, r: ['けい', 'ケイ'], m: ["scenery","view"] },
  { k: '落', n: 3, f: 420, r: ['らく', 'ラク'], m: ["fall","come down","drop","hamlet","village"] },
  { k: '好', n: 3, f: 423, r: ['こう', 'コウ'], m: ["fond","like something","pleasing"] },
  { k: '退', n: 3, f: 424, r: ['たい', 'タイ'], m: ["retreat","expel","reject","repel","resign","retire","withdraw"] },
  { k: '頭', n: 3, f: 433, r: ['ず', 'ズ', 'と', 'ト', 'とう', 'トウ', 'あたま', 'アタマ', 'かしら', 'カシラ', 'かぶり'], m: ["head","counter for large animals"] },
  { k: '負', n: 3, f: 443, r: ['ふ', 'フ'], m: ["defeat","-","assume a responsibility","bear","minus","negative","owe"] },
  { k: '渡', n: 3, f: 446, r: ['と', 'ト'], m: ["transit","cross","deliver","diameter","ferry","ford","import","migrate"] },
  { k: '失', n: 3, f: 447, r: ['しつ'], m: ["lose","disadvantage","error","fault","loss"] },
  { k: '差', n: 3, f: 449, r: ['さ', 'サ'], m: ["distinction","balance","difference","discrepancy","margin","variation"] },
  { k: '末', n: 3, f: 456, r: ['ばつ', 'バツ', 'まつ', 'マツ', 'うら', 'ウラ', 'うれ', 'ウレ', 'すえ', 'スエ'], m: ["extremity","close","end","posterity","powder","tip"] },
  { k: '守', n: 3, f: 457, r: ['しゅ', 'シュ', 'す', 'ス', 'かみ', 'カミ', 'もり', 'モリ'], m: ["guard","defend","obey","protect"] },
  { k: '若', n: 3, f: 458, r: ['じゃく', 'にゃ', 'ニャ'], m: ["young","if","immature","low number","perhaps","possibly"] },
  { k: '種', n: 3, f: 461, r: ['しゅ', 'シュ', 'たね', 'タネ'], m: ["species","class","kind","seed","variety"] },
  { k: '美', n: 3, f: 462, r: ['び', 'ビ', 'み', 'ミ'], m: ["beauty","beautiful"] },
  { k: '命', n: 3, f: 465, r: ['みょう', 'めい', 'メイ', 'いのち'], m: ["fate","appoint","command","decree","destiny","life"] },
  { k: '福', n: 3, f: 467, r: ['ふく', 'フク'], m: ["blessing","fortune","luck","wealth"] },
  { k: '望', n: 3, f: 470, r: ['ぼう', 'ボウ', 'もう', 'モウ', 'もち', 'モチ'], m: ["ambition","aspire to","desire","expect","full moon","hope"] },
  { k: '非', n: 3, f: 472, r: ['ひ', 'ヒ'], m: ["un-","injustice","mistake","negative","non-"] },
  { k: '観', n: 3, f: 476, r: ['かん', 'カン'], m: ["outlook","appearance","condition","look","view"] },
  { k: '察', n: 3, f: 477, r: ['さつ', 'サツ'], m: ["guess","judge","presume","surmise","understand"] },
  { k: '段', n: 3, f: 479, r: ['たん', 'タン', 'だん', 'ダン'], m: ["grade","stairs","steps"] },
  { k: '横', n: 3, f: 480, r: ['おう', 'オウ', 'よこ', 'ヨコ'], m: ["sideways","horizontal","perverse","side","unreasonable","width","woof"] },
  { k: '深', n: 3, f: 484, r: ['しん', 'シン'], m: ["deep","heighten","intensify","strengthen"] },
  { k: '申', n: 3, f: 492, r: ['しん', 'シン', 'さる', 'サル'], m: ["speaketh","3-5PM","have the honor to","ninth sign of Chinese zodiac","sign of the monkey"] },
  { k: '様', n: 3, f: 493, r: ['しょう', 'ショウ', 'よう', 'ヨウ', 'さま', 'サマ', 'さん', 'サン'], m: ["Esq.","manner","polite suffix","situation","way"] },
  { k: '財', n: 3, f: 494, r: ['さい', 'サイ', 'ざい', 'ぞく', 'たから', 'タカラ'], m: ["property","assets","money","wealth"] },
  { k: '港', n: 3, f: 495, r: ['こう', 'コウ', 'みなと', 'ミナト'], m: ["harbor"] },
  { k: '識', n: 3, f: 496, r: ['しき', 'シキ'], m: ["discriminating","know","write"] },
  { k: '呼', n: 3, f: 498, r: ['こ', 'コ'], m: ["call","call out to","invite"] },
  { k: '達', n: 3, f: 500, r: ['たつ', 'タツ', 'だ', 'ダ'], m: ["accomplished","arrive","attain","reach"] },
  { k: '良', n: 3, f: 501, r: ['りょう', 'リョウ'], m: ["good","pleasing","skilled"] },
  { k: '候', n: 3, f: 510, r: ['こう', 'コウ', 'そうろう'], m: ["climate","expect","season","wait for","weather"] },
  { k: '程', n: 3, f: 514, r: ['てい', 'テイ', 'ほど'], m: ["extent","amount","degree","distance","formula","law","limits"] },
  { k: '満', n: 3, f: 515, r: ['ばん', 'バン', 'まん', 'マン'], m: ["full","enough","fullness","satisfy"] },
  { k: '敗', n: 3, f: 516, r: ['はい', 'ハイ'], m: ["failure","defeat","reversal"] },
  { k: '値', n: 3, f: 518, r: ['ち', 'チ', 'あたい', 'アタイ', 'ね', 'ネ'], m: ["price","cost","value"] },
  { k: '突', n: 3, f: 521, r: ['か', 'カ', 'とつ'], m: ["stab","collision","pierce","prick","protruding","sudden","thrust"] },
  { k: '光', n: 3, f: 527, r: ['こう', 'コウ', 'ひかり', 'ヒカリ'], m: ["ray","light"] },
  { k: '路', n: 3, f: 529, r: ['る', 'ル', 'ろ', 'ロ', 'みち', 'ミチ'], m: ["path","distance","road","route"] },
  { k: '科', n: 3, f: 531, r: ['か', 'カ'], m: ["department","course","section"] },
  { k: '積', n: 3, f: 541, r: ['せき', 'セキ'], m: ["volume","acreage","amass","contents","load","pile up","product (x*y)","stack"] },
  { k: '他', n: 3, f: 543, r: ['た', 'タ', 'ほか'], m: ["other","another","the others"] },
  { k: '処', n: 3, f: 547, r: ['しょ', 'ショ', 'ところ', 'トコロ'], m: ["dispose","act","behave","condemn","deal with","manage","place","sentence"] },
  { k: '太', n: 3, f: 552, r: ['た', 'タ', 'たい', 'タイ'], m: ["plump","big around","thick"] },
  { k: '客', n: 3, f: 557, r: ['かく', 'カク', 'きゃく'], m: ["guest","client","customer","visitor"] },
  { k: '否', n: 3, f: 561, r: ['ひ', 'ヒ', 'いな', 'イナ', 'いや', 'イヤ'], m: ["negate","decline","deny","no","noes","refuse"] },
  { k: '師', n: 3, f: 563, r: ['し', 'シ', 'いくさ', 'イクサ'], m: ["expert","army (incl. counter)","exemplar","master","model","teacher","war"] },
  { k: '登', n: 3, f: 566, r: ['しょう', 'ショウ', 'ちょう', 'チョウ', 'と', 'ト', 'とう', 'トウ', 'どう', 'ドウ'], m: ["ascend","climb up"] },
  { k: '易', n: 3, f: 571, r: ['い', 'イ', 'えき'], m: ["easy","divination","fortune-telling","ready to","simple"] },
  { k: '速', n: 3, f: 576, r: ['そく', 'ソク'], m: ["quick","fast"] },
  { k: '存', n: 3, f: 577, r: ['そん', 'ソン', 'ぞん', 'ゾン'], m: ["suppose","be aware of","believe","exist","feel"] },
  { k: '飛', n: 3, f: 580, r: ['ひ', 'ヒ'], m: ["fly","scatter","skip (pages)"] },
  { k: '殺', n: 3, f: 581, r: ['さい', 'サイ', 'さつ', 'サツ', 'せつ', 'セツ'], m: ["kill","butcher","diminish","murder","reduce","slice off","split","spoil"] },
  { k: '号', n: 3, f: 585, r: ['ごう', 'ゴウ'], m: ["nickname","call","item","name","number","pseudonym","title"] },
  { k: '単', n: 3, f: 586, r: ['たん', 'タン', 'ひとえ'], m: ["simple","merely","one","single"] },
  { k: '座', n: 3, f: 588, r: ['ざ', 'ザ'], m: ["squat/sit","cushion","gathering","seat","sit","squat"] },
  { k: '破', n: 3, f: 590, r: ['は', 'ハ'], m: ["rend","break","defeat","destroy","frustrate","rip","tear"] },
  { k: '除', n: 3, f: 594, r: ['じ', 'ジ', 'じょ', 'ジョ'], m: ["exclude","abolish","cancel","division (x/3)","except","remove"] },
  { k: '完', n: 3, f: 595, r: ['かん', 'カン'], m: ["perfect","completion","end"] },
  { k: '降', n: 3, f: 596, r: ['こう', 'コウ', 'ご', 'ゴ'], m: ["descend","fall","precipitate","surrender"] },
  { k: '責', n: 3, f: 598, r: ['せき', 'セキ'], m: ["blame","censure","condemn"] },
  { k: '捕', n: 3, f: 604, r: ['ほ', 'ホ'], m: ["catch","capture"] },
  { k: '危', n: 3, f: 606, r: ['き', 'キ'], m: ["dangerous","fear","uneasy"] },
  { k: '給', n: 3, f: 615, r: ['きゅう', 'キュウ'], m: ["salary","allow","bestow on","gift","grant","wage"] },
  { k: '苦', n: 3, f: 623, r: ['く', 'ク'], m: ["suffering","feel bitter","hardship","scowl","trial","worry"] },
  { k: '迎', n: 3, f: 625, r: ['ゲイ'], m: ["welcome","greet","meet"] },
  { k: '園', n: 3, f: 628, r: ['えん', 'エン', 'その', 'ソノ'], m: ["park","farm","garden","yard"] },
  { k: '具', n: 3, f: 629, r: ['ぐ', 'グ'], m: ["tool","counter for armor, suits, sets of furniture","ingredients","means","possess","utensil"] },
  { k: '辞', n: 3, f: 633, r: ['じ', 'ジ'], m: ["resign","expression","term","word"] },
  { k: '因', n: 3, f: 636, r: ['いん', 'イン'], m: ["cause","be associated with","be limited to","depend on","factor"] },
  { k: '馬', n: 3, f: 639, r: ['ば', 'バ', 'うま', 'ウマ', 'ま', 'マ'], m: ["horse"] },
  { k: '愛', n: 3, f: 640, r: ['あい', 'アイ', 'まな', 'マナ'], m: ["love","affection","favourite"] },
  { k: '富', n: 3, f: 644, r: ['ふ', 'フ', 'ふう', 'フウ', 'とみ', 'トミ'], m: ["wealth","abundant","enrich"] },
  { k: '彼', n: 3, f: 648, r: ['ひ', 'ヒ', 'かの', 'カノ', 'かれ', 'カレ'], m: ["he","that","the"] },
  { k: '未', n: 3, f: 650, r: ['び', 'ビ', 'み', 'ミ', 'ひつじ', 'ヒツジ'], m: ["not yet","1-3PM","eighth sign of Chinese zodiac","even now","hitherto","sign of the ram","still","un-"] },
  { k: '舞', n: 3, f: 655, r: ['ぶ', 'ブ', 'まい', 'マイ'], m: ["dance","circle","flit","wheel"] },
  { k: '亡', n: 3, f: 661, r: ['ぼう', 'ボウ', 'もう', 'モウ'], m: ["deceased","dying","perish","the late"] },
  { k: '冷', n: 3, f: 667, r: ['れい', 'レイ'], m: ["cool","chill","cold (beer, person)"] },
  { k: '適', n: 3, f: 670, r: ['てき', 'テキ'], m: ["suitable","capable","occasional","qualified","rare"] },
  { k: '婦', n: 3, f: 671, r: ['ふ', 'フ', 'よめ'], m: ["lady","bride","wife","woman"] },
  { k: '寄', n: 3, f: 673, r: ['き', 'キ'], m: ["draw near","bring near","collect","forward","gather","send","stop in"] },
  { k: '込', n: 3, f: 675, r: ['こ', 'コ'], m: ["crowded","(kokuji)","in bulk","included","mixture"] },
  { k: '顔', n: 3, f: 676, r: ['がん', 'ガン', 'かお', 'カオ'], m: ["face","expression"] },
  { k: '類', n: 3, f: 678, r: ['るい', 'ルイ'], m: ["sort","class","genus","kind","variety"] },
  { k: '余', n: 3, f: 680, r: ['よ', 'ヨ'], m: ["too much","myself","other","remainder","surplus"] },
  { k: '王', n: 3, f: 684, r: ['おう', 'オウ'], m: ["king","magnate","rule"] },
  { k: '返', n: 3, f: 685, r: ['へん', 'ヘン'], m: ["return","answer","fade","repay"] },
  { k: '妻', n: 3, f: 691, r: ['さい', 'サイ', 'つま'], m: ["wife","spouse"] },
  { k: '背', n: 3, f: 696, r: ['はい', 'ハイ', 'せ', 'セ', 'せい', 'セイ'], m: ["stature","back","behind","defy","disobey","go back on","height","rebel"] },
  { k: '熱', n: 3, f: 700, r: ['ねつ'], m: ["heat","fever","mania","passion","temperature"] },
  { k: '宿', n: 3, f: 701, r: ['しゅく', 'やど'], m: ["inn","be pregnant","dwell","dwelling","home","lodge","lodging","relay station"] },
  { k: '薬', n: 3, f: 702, r: ['やく', 'ヤク', 'くすり', 'クスリ'], m: ["medicine","benefit","chemical","enamel","gunpowder"] },
  { k: '険', n: 3, f: 707, r: ['けん', 'ケン'], m: ["precipitous","impregnable position","inaccessible place","sharp eyes","steep place"] },
  { k: '頼', n: 3, f: 708, r: ['らい', 'ライ'], m: ["trust","request"] },
  { k: '覚', n: 3, f: 710, r: ['かく', 'カク'], m: ["memorize","awake","learn","remember","sober up"] },
  { k: '船', n: 3, f: 713, r: ['せん', 'セン', 'フネ'], m: ["ship","boat"] },
  { k: '途', n: 3, f: 717, r: ['と', 'ト', 'みち', 'ミチ'], m: ["route","road","way"] },
  { k: '許', n: 3, f: 720, r: ['きょ', 'もと', 'モト'], m: ["permit","approve"] },
  { k: '抜', n: 3, f: 726, r: ['はい', 'ハイ', 'はつ', 'ハツ', 'ばつ', 'バツ'], m: ["slip out","extract","omit","pilfer","pull out","quote","remove"] },
  { k: '便', n: 3, f: 729, r: ['びん', 'ビン', 'べん', 'ベン'], m: ["convenience","chance","excrement","facility","feces","letter"] },
  { k: '留', n: 3, f: 731, r: ['りゅう', 'リュウ', 'る', 'ル'], m: ["detain","fasten","halt","stop"] },
  { k: '罪', n: 3, f: 732, r: ['ざい', 'つみ', 'ツミ'], m: ["guilt","blame","crime","fault","offense","sin"] },
  { k: '努', n: 3, f: 749, r: ['ど', 'ド'], m: ["toil","as much as possible","diligent"] },
  { k: '精', n: 3, f: 752, r: ['しょう', 'ショウ', 'せい', 'セイ'], m: ["refined","energy","excellence","fairy","ghost","purity","semen","skill","vitality"] },
  { k: '散', n: 3, f: 758, r: ['さん', 'サン', 'ばら', 'バラ'], m: ["scatter","disperse","spend","squander"] },
  { k: '静', n: 3, f: 764, r: ['じょう', 'せい', 'セイ'], m: ["quiet"] },
  { k: '婚', n: 3, f: 767, r: ['こん', 'コン'], m: ["marriage"] },
  { k: '喜', n: 3, f: 769, r: ['き', 'キ'], m: ["rejoice","take pleasure in"] },
  { k: '浮', n: 3, f: 776, r: ['ふ', 'フ'], m: ["floating","float","rise to surface"] },
  { k: '絶', n: 3, f: 784, r: ['ぜつ'], m: ["discontinue","abstain","be beyond","cut off","interrupt","peerless","sever","suppress","unparalleled","without match"] },
  { k: '幸', n: 3, f: 786, r: ['こう', 'コウ', 'さち', 'サチ'], m: ["happiness","blessing","fortune"] },
  { k: '押', n: 3, f: 789, r: ['おう', 'オウ'], m: ["push","attach","check","do in spite of","press","seal","seize","shove","stop","subdue","weight"] },
  { k: '倒', n: 3, f: 791, r: ['とう', 'トウ', 'さかさ'], m: ["overthrow","break down","collapse","drop","fall"] },
  { k: '等', n: 3, f: 798, r: ['とう', 'トウ', 'など'], m: ["etc.","and so forth","class (first)","equal","quality","similar"] },
  { k: '老', n: 3, f: 803, r: ['ろう', 'ロウ'], m: ["old man","grow old","old age"] },
  { k: '曲', n: 3, f: 810, r: ['きょく', 'くま', 'クマ'], m: ["bend","composition","crooked","curve","fault","injustice","lean","melody","music","perverse","pleasure"] },
  { k: '払', n: 3, f: 813, r: ['ひつ', 'ふつ', 'フツ'], m: ["pay","banish","clear out","dispose of","prune"] },
  { k: '庭', n: 3, f: 816, r: ['てい', 'テイ', 'にわ', 'ニワ'], m: ["courtyard","garden","yard"] },
  { k: '徒', n: 3, f: 817, r: ['と', 'ト', 'あだ', 'アダ', 'いたずら', 'イタズラ'], m: ["junior","emptiness","ephemeral thing","futility","gang","on foot","party","people","set","uselessness","vanity"] },
  { k: '勤', n: 3, f: 830, r: ['きん', 'キン', 'ごん', 'ゴン'], m: ["diligence","become employed","serve"] },
  { k: '遅', n: 3, f: 833, r: ['ち', 'チ'], m: ["slow","back","late","later"] },
  { k: '居', n: 3, f: 836, r: ['きょ', 'こ', 'コ'], m: ["reside","exist","live with","to be"] },
  { k: '雑', n: 3, f: 839, r: ['ざつ', 'ぞう', 'ゾウ'], m: ["miscellaneous"] },
  { k: '招', n: 3, f: 840, r: ['しょう', 'ショウ'], m: ["beckon","engage","invite","summon"] },
  { k: '困', n: 3, f: 843, r: ['こん', 'コン'], m: ["quandary","annoyed","become distressed"] },
  { k: '欠', n: 3, f: 860, r: ['けつ', 'けん', 'ケン'], m: ["lack","fail","gap"] },
  { k: '更', n: 3, f: 861, r: ['こう', 'コウ', 'さら', 'サラ'], m: ["grow late","again","further","more and more","night watch","of course","renew","renovate","sit up late"] },
  { k: '刻', n: 3, f: 866, r: ['こく', 'コク'], m: ["engrave","carving","chop","cut fine","hash","mince","time"] },
  { k: '賛', n: 3, f: 868, r: ['さん', 'サン'], m: ["approve","agree with","assist","praise","title or inscription on picture"] },
  { k: '抱', n: 3, f: 871, r: ['ほう', 'ホウ'], m: ["embrace","hold in arms","hug"] },
  { k: '犯', n: 3, f: 874, r: ['はん', 'ハン', 'ぼん', 'ボン'], m: ["crime","offense","sin"] },
  { k: '恐', n: 3, f: 878, r: ['きょう', 'キョウ'], m: ["fear","awe","dread"] },
  { k: '息', n: 3, f: 882, r: ['そく', 'ソク', 'いき'], m: ["breath","coming to an end","interest (on money)","nuture","respiration","rest","son"] },
  { k: '遠', n: 3, f: 887, r: ['えん', 'エン', 'おん', 'オン'], m: ["distant","far"] },
  { k: '戻', n: 3, f: 890, r: ['れい', 'レイ'], m: ["re-","go backwards","restore","resume","return","revert"] },
  { k: '願', n: 3, f: 894, r: ['がん', 'ガン'], m: ["petition","hope","request","vow","wish"] },
  { k: '絵', n: 3, f: 895, r: ['え', 'エ', 'かい', 'カイ'], m: ["picture","drawing","painting","sketch"] },
  { k: '越', n: 3, f: 897, r: ['えつ', 'エツ', 'おつ', 'オツ'], m: ["surpass","Vietnam","cross over","exceed","move to"] },
  { k: '欲', n: 3, f: 902, r: ['よく'], m: ["longing","covetousness","craving","desire","greed","passion"] },
  { k: '痛', n: 3, f: 903, r: ['つう'], m: ["pain","bruise","damage","hurt"] },
  { k: '笑', n: 3, f: 913, r: ['しょう', 'ショウ'], m: ["laugh"] },
  { k: '互', n: 3, f: 914, r: ['ご', 'ゴ'], m: ["mutually","reciprocally","together"] },
  { k: '束', n: 3, f: 918, r: ['そく', 'ソク', 'たば', 'タバ', 'つか', 'ツカ'], m: ["bundle","control","govern","manage","ream","sheaf","tie in bundles"] },
  { k: '似', n: 3, f: 923, r: ['じ', 'ジ'], m: ["becoming/similar","becoming","counterfeit","imitate","resemble","suitable"] },
  { k: '列', n: 3, f: 927, r: ['れ', 'レ', 'れつ'], m: ["file","column","rank","row","tier"] },
  { k: '探', n: 3, f: 930, r: ['たん', 'タン'], m: ["grope","look for","search"] },
  { k: '逃', n: 3, f: 931, r: ['とう', 'トウ'], m: ["escape","evade","flee","set free","shirk"] },
  { k: '遊', n: 3, f: 941, r: ['ゆ', 'ユ', 'ゆう', 'ユウ'], m: ["play"] },
  { k: '迷', n: 3, f: 942, r: ['めい', 'メイ'], m: ["astray","be perplexed","err","illusion","in doubt","lost"] },
  { k: '夢', n: 3, f: 943, r: ['ぼう', 'ボウ', 'む', 'ム', 'ゆめ', 'ユメ'], m: ["dream","illusion","vision"] },
  { k: '君', n: 3, f: 947, r: ['くん', 'クン', 'きみ', 'キミ'], m: ["old boy","male name suffix","mister","ruler","you"] },
  { k: '閉', n: 3, f: 951, r: ['へい', 'ヘイ'], m: ["closed","shut"] },
  { k: '緒', n: 3, f: 952, r: ['しょ', 'ショ', 'ちょ', 'チョ', 'お', 'オ'], m: ["thong","beginning","cord","end","inception","mental or emotional state","strap"] },
  { k: '折', n: 3, f: 962, r: ['しゃく', 'シャク', 'せつ', 'セツ', 'おり', 'オリ'], m: ["fold","bend","break","fracture","submit","yield"] },
  { k: '草', n: 3, f: 967, r: ['そう', 'ソウ', 'くさ', 'クサ'], m: ["grass","draft","herbs","pasture","weeds","write"] },
  { k: '暮', n: 3, f: 978, r: ['ぼ', 'ボ'], m: ["livelihood","evening","make a living","season's end","spend time","twilight"] },
  { k: '酒', n: 3, f: 1006, r: ['しゅ', 'シュ', 'さけ', 'サケ'], m: ["sake","alcohol"] },
  { k: '悲', n: 3, f: 1014, r: ['ひ', 'ヒ'], m: ["sad","deplore","grieve","regret"] },
  { k: '晴', n: 3, f: 1022, r: ['せい', 'セイ'], m: ["clear up"] },
  { k: '掛', n: 3, f: 1027, r: ['かい', 'カイ', 'けい', 'ケイ', 'かかり'], m: ["hang","arrive at","depend","pour","suspend","tax"] },
  { k: '到', n: 3, f: 1032, r: ['とう', 'トウ'], m: ["arrival","attain","proceed","reach","result in"] },
  { k: '寝', n: 3, f: 1034, r: ['しん', 'シン'], m: ["lie down","bed","remain unsold","rest","sleep"] },
  { k: '暗', n: 3, f: 1040, r: ['あん', 'アン'], m: ["darkness","be blinded","disappear","grow dark","informal","shade"] },
  { k: '盗', n: 3, f: 1051, r: ['とう', 'トウ'], m: ["steal","pilfer","rob"] },
  { k: '吸', n: 3, f: 1054, r: ['きゅう', 'キュウ'], m: ["suck","imbibe","inhale","sip"] },
  { k: '陽', n: 3, f: 1071, r: ['よう', 'ヨウ', 'ひ', 'ヒ'], m: ["sunshine","daytime","heaven","male","positive","yang principle"] },
  { k: '御', n: 3, f: 1087, r: ['ぎょ', 'ギョ', 'ご', 'ゴ'], m: ["honorable","govern","manipulate"] },
  { k: '歯', n: 3, f: 1106, r: ['し', 'シ', 'は', 'ハ', 'よわい'], m: ["tooth","cog"] },
  { k: '忘', n: 3, f: 1129, r: ['ぼう', 'ボウ'], m: ["forget"] },
  { k: '雪', n: 3, f: 1131, r: ['せつ', 'セツ', 'ゆき', 'ユキ'], m: ["snow"] },
  { k: '吹', n: 3, f: 1133, r: ['すい', 'スイ'], m: ["blow","breathe","emit","puff","smoke"] },
  { k: '娘', n: 3, f: 1145, r: ['じょう', 'こ', 'コ'], m: ["daughter","girl"] },
  { k: '誤', n: 3, f: 1150, r: ['ご', 'ゴ'], m: ["mistake","do wrong","err","mislead"] },
  { k: '洗', n: 3, f: 1168, r: ['せん', 'セン'], m: ["wash","inquire into","probe"] },
  { k: '慣', n: 3, f: 1177, r: ['かん', 'カン'], m: ["accustomed","become experienced","get used to"] },
  { k: '礼', n: 3, f: 1185, r: ['らい', 'ライ', 'れい', 'レイ'], m: ["salute/salutation","bow","ceremony","remuneration","salute","thanks"] },
  { k: '窓', n: 3, f: 1186, r: ['す', 'ス', 'そう', 'ソウ', 'まど'], m: ["window","pane"] },
  { k: '昔', n: 3, f: 1197, r: ['しゃく', 'シャク', 'せき', 'セキ', 'むかし'], m: ["once upon a time","antiquity","old times"] },
  { k: '貧', n: 3, f: 1211, r: ['ひん', 'ヒン', 'びん', 'ビン'], m: ["poverty","poor"] },
  { k: '怒', n: 3, f: 1221, r: ['ど', 'ド', 'ぬ'], m: ["angry","be offended"] },
  { k: '泳', n: 3, f: 1223, r: ['えい', 'エイ'], m: ["swim"] },
  { k: '祖', n: 3, f: 1226, r: ['そ', 'ソ'], m: ["ancestor","founder","pioneer"] },
  { k: '杯', n: 3, f: 1235, r: ['はい', 'ハイ'], m: ["cupfuls","counter for cupfuls","glass","toast","wine glass"] },
  { k: '疲', n: 3, f: 1263, r: ['ひ', 'ヒ'], m: ["exhausted/tired","exhausted","tire","weary"] },
  { k: '皆', n: 3, f: 1267, r: ['かい', 'カイ', 'みな', 'ミナ', 'みんな', 'ミンナ'], m: ["all","everything"] },
  { k: '鳴', n: 3, f: 1279, r: ['めい', 'メイ'], m: ["chirp","bark","cry","echo","honk","ring","sound"] },
  { k: '腹', n: 3, f: 1286, r: ['ふく', 'フク', 'はら', 'ハラ'], m: ["abdomen","belly","stomach"] },
  { k: '煙', n: 3, f: 1290, r: ['えん', 'エン', 'けむり'], m: ["smoke"] },
  { k: '眠', n: 3, f: 1315, r: ['みん', 'ミン'], m: ["sleep","die","sleepy"] },
  { k: '怖', n: 3, f: 1325, r: ['ふ', 'フ', 'ほ', 'ホ'], m: ["dreadful","be frightened","fearful"] },
  { k: '耳', n: 3, f: 1328, r: ['じ', 'ジ', 'みみ', 'ミミ'], m: ["ear"] },
  { k: '頂', n: 3, f: 1350, r: ['ちょう', 'チョウ', 'いただき'], m: ["place on the head","peak","receive","summit","top","top of head"] },
  { k: '箱', n: 3, f: 1357, r: ['そう', 'ソウ', 'はこ', 'ハコ'], m: ["box","bin","case","chest","railway car"] },
  { k: '晩', n: 3, f: 1424, r: ['ばん', 'バン'], m: ["nightfall","night"] },
  { k: '寒', n: 3, f: 1456, r: ['かん', 'カン'], m: ["cold"] },
  { k: '髪', n: 3, f: 1474, r: ['はつ', 'ハツ', 'かみ', 'カミ'], m: ["hair of the head"] },
  { k: '忙', n: 3, f: 1475, r: ['ぼう', 'ボウ', 'もう', 'モウ'], m: ["busy","occupied","restless"] },
  { k: '才', n: 3, f: 1497, r: ['さい', 'サイ'], m: ["genius","cubic shaku","years old"] },
  { k: '靴', n: 3, f: 1561, r: ['か', 'カ', 'くつ'], m: ["shoes"] },
  { k: '恥', n: 3, f: 1575, r: ['ち', 'チ', 'はじ', 'ハジ'], m: ["shame","dishonor"] },
  { k: '偶', n: 3, f: 1602, r: ['ぐう', 'たま', 'タマ'], m: ["accidentally","couple","even number","man & wife","same kind"] },
  { k: '偉', n: 3, f: 1639, r: ['い', 'イ'], m: ["admirable","conceited","excellent","famous","greatness","remarkable"] },
  { k: '猫', n: 3, f: 1702, r: ['びょう', 'ねこ', 'ネコ'], m: ["cat"] },
  { k: '幾', n: 3, f: 1725, r: ['き', 'キ'], m: ["how many","how far","how long","how much","several","some"] },
];
